version: '3.9'

services:
  langschoolmsql:
    image: mysql:8
    container_name: langschoolmsql
    restart: always
    ports:
      - '3307:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=mysqlpass
      - MYSQL_USER=mysqluser
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_HOST=%
      - LANG=C.UTF-8
      - lower_case_table_names=1
    volumes:
      - mysqldbvolume:/var/lib/mysql
volumes:
  mysqldbvolume: